language: python

python:
  - "2.6"
  - "2.7"
#  - "3.2" # PyMox mocking library is incompatibile with Python 3 so tests will fail

install:
    - pip install --use-mirrors argparse mox

script: tests/runtest.py -f
